### ISSUE TITLE
ref non affiché

### ISSUE THREAD

**Issue by Bibi56** [shindere/metro-stories#1]
Afficher Sortie <ref> <name>.
Si <name> comporte Sortie alors idéalement nettoyer les données ;-) à défaut ne pas afficher que ce qui est après le nombre suivant Sortie.

**Comment by shindere** [comment]
Merci beaucoup pour le rapport.

Je crois que le problème est résolu et vais donc fermer le ticket mais
n'hésite pas à le rouvrir si tu penses que les hcoses devraient être faites
autrement.

Pour info, j'essaie d'afficher les données OSM aussi "brutes" que
possible afin de détecter les problèmes.
