### ISSUE TITLE
pas de Champs adresse pour relancer une recherche quand on a le résultat

### ISSUE THREAD

**Issue by vinber** [shindere/metro-stories#2]
Lorsque l'on a un résultat par exemple les 5 bouches de métro les plus proches ou quand on a pas de résultat (j'ai testé à Bordeaux, il n'y a pas de métro), il n'y a pas la possibilité de refaire une recherche d'adresse.

On doit revenir en arrière :)

**Comment by shindere** [comment]
Merci beaucoup, c'est une bonne suggestion et ça devrait être corrigé
maintenant!
Tout autre commentaire est le bienvenu.
